version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
      - 'npm'
    ignore:
      - dependency-name: 'typescript'
      - dependency-name: 'typedoc'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'chore(deps)'
